definitions:
  models.Quote:
    properties:
      deliveryDate:
        example: "2023-02-24T00:00:00Z"
        type: string
      deliveryaddress:
        example: best st
        type: string
      gallonsrequested:
        example: 99999
        type: integer
      id:
        example: 63f79148c3a63a346225fd99
        type: string
      suggestedpricepergallon:
        example: 1.74
        type: number
      totalamountdue:
        example: 173998.26
        type: number
      userId:
        example: 63f78fc8c3a63a346225fd96
        type: string
    type: object
  models.User:
    properties:
      address1:
        example: coolsvile avvae
        type: string
      address2:
        example: billion ave
        type: string
      city:
        example: Houstonian
        type: string
      fullname:
        example: zenyatta man
        type: string
      id:
        example: 63f78fc8c3a63a346225fd96
        type: string
      password:
        example: bdeac530209b16657065661aa11fcdd85b21b01a
        type: string
      quotes:
        example: 0
        type: integer
      state:
        example: AZ
        type: string
      username:
        example: zamzang
        type: string
      zipcode:
        example: 827392
        type: integer
    type: object
  users.CreateUserBody:
    properties:
      address1:
        example: coolsvile avvae
        type: string
      address2:
        example: billion ave
        type: string
      city:
        example: Houstonian
        type: string
      fullname:
        example: zenyatta man
        type: string
      password:
        example: notpassword
        type: string
      state:
        example: AZ
        type: string
      username:
        example: zamzang
        type: string
      zipcode:
        example: 827392
        type: integer
    type: object
  users.LoginUserBody:
    properties:
      password:
        example: notpassword
        type: string
      username:
        example: zamzang
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /quotes/{id}:
    get:
      consumes:
      - application/json
      description: gets a quote from its id
      parameters:
      - description: Quote ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Queried Quote
          schema:
            $ref: '#/definitions/models.Quote'
        "400":
          description: Invalid ID format
          schema:
            type: string
        "404":
          description: Quote not found
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Get Quote
      tags:
      - quotes
  /token:
    get:
      description: Returns your authorization cookie, if it exists
      produces:
      - text/plain
      responses:
        "200":
          description: Cookie Exists
          schema:
            type: string
        "404":
          description: No Cookie
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Get Token
      tags:
      - token
  /token/validate:
    get:
      description: Validates your auth token from your browser cookie
      responses:
        "200":
          description: Authorized
          schema:
            type: ""
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: No Cookie
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Validate Token
      tags:
      - token
  /users:
    post:
      consumes:
      - application/json
      description: Creates a new user from user info
      parameters:
      - description: Create User Request Body
        in: body
        name: createuserbody
        required: true
        schema:
          $ref: '#/definitions/users.CreateUserBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created User's ID
          schema:
            type: string
        "400":
          description: Bad User Entry
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Create User
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Gain an auth jwt cookie for a user by providing username and password
      parameters:
      - description: Login User Request Body
        in: body
        name: loginuserbody
        required: true
        schema:
          $ref: '#/definitions/users.LoginUserBody'
      responses:
        "200":
          description: Obtained Auth
          schema:
            type: ""
        "400":
          description: Bad Request Formation
          schema:
            type: string
        "401":
          description: Wrong Password
          schema:
            type: string
        "404":
          description: User Not Found
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Login User
      tags:
      - users
  /users/me:
    get:
      description: returns your user info from your auth cookie
      produces:
      - application/json
      responses:
        "200":
          description: Current User
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Not authorized as any user
          schema:
            type: string
        "500":
          description: Unknown internal server error
          schema:
            type: string
      summary: Get User
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    description: Basic password login token auth, stored in a cookie for convenience
    in: cookie
    name: Authorization
    type: apiKey
swagger: "2.0"
